CI: pre-push-hook: abort if pipenv is not installed

diff --git a/.hooks/pre-push b/.hooks/pre-push
--- a/.hooks/pre-push
+++ b/.hooks/pre-push
@@ -2,6 +2,37 @@
 
 set -e
 
+# Check if pipenv is installed
+command -v pipenv >/dev/null 2>&1 || {
+    echo >&2 "pipenv is not installed. Aborting. Please install it and try again."
+    exit 1
+}
+
+# Check if shellcheck is installed
+command -v shellcheck >/dev/null 2>&1 || {
+    echo >&2 "shellcheck is not installed. Aborting. Please install it and try again."
+    exit 1
+}
+
+
+isort_extra_args="--check-only --diff"
+black_extra_args="--check --diff"
+fixing="false"
+
+for arg in "$@"; do
+  case $arg in
+    --fix)
+      isort_extra_args=""
+      black_extra_args=""
+      fixing="true"
+      ;;
+    *)
+      echo "Unknown argument: $arg"
+      exit 1
+      ;;
+  esac
+done
+
 echo "Running pre push hook!"
 repository_path=$(git rev-parse --show-toplevel)
 tag_name=$(git tag --points-at=HEAD | head -n 1)
