.hooks: Modify to use core project
* Modify .hooks to use the core pyproject.toml to install all needed
  depencies

diff --git a/.hooks/pre-push b/.hooks/pre-push
--- a/.hooks/pre-push
+++ b/.hooks/pre-push
@@ -1,26 +1,11 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e
 
-# Check if the required Python version is available
-PYTHON_VERSION=$(grep -oP 'python\s*=\s*"[^0-9]*\K[0-9]+\.[0-9]+' pyproject.toml)
-command -v "python$PYTHON_VERSION" >/dev/null 2>&1 || {
-    if [ "$(command -v pyenv)" ]; then
-        echo "Pyenv is available, switching local Python version to $PYTHON_VERSION"
-        pyenv install -fs "$PYTHON_VERSION"
-        pyenv local "$PYTHON_VERSION"
-    else
-        cat >&2 <<EOF
-Python $PYTHON_VERSION is not available. Aborting.
-If your Linux distribution doesn't provide it, consider using Pyenv:
-    1. Install Pyenv using your Linux distribution package manager
-    2. Run the following commands:
-        pyenv install $PYTHON_VERSION
-        pyenv local $PYTHON_VERSION
-For more information about pyenv, please visit https://github.com/pyenv/pyenv#readme
-EOF
+# Check if uv is installed
+command -v uv >/dev/null 2>&1 || {
+    echo >&2 "uv is not installed. Aborting. Please install it and try again."
     exit 1
-    fi
 }
 
 # Check if poetry is installed
@@ -44,8 +29,10 @@ command -v parallel >/dev/null 2>&1 || {
 nginxVersion=1.22.1
 docker run --rm -v ${PWD}/core/tools/nginx/:/nginx/:ro nginx:$nginxVersion nginx -c /nginx/nginx.conf -t
 
-poetry install
-. "$(poetry env info --path)/bin/activate"
+# Install required python packages and activate the virtual environment
+uv sync --all-groups --project ${PWD}/core && source ${PWD}/core/.venv/bin/activate
+export VIRTUAL_ENV=${PWD}/core/.venv
+export PATH="${VIRTUAL_ENV}/bin:$PATH"
 
 # download some required files if they are not present
 echo "installing mavlink-server"
@@ -97,6 +84,9 @@ echo "Running shellcheck..."
 #SC2086: Allow word splitting
 git ls-files '*.sh' | xargs -L 1 shellcheck --exclude=SC2005,SC2015,SC2046,SC2048,SC2086
 
+# Goes to the core directory
+cd core
+
 echo "Running isort.."
 # Run isort for each python project
 dirname $(git ls-files "$repository_path/*/setup.py") | xargs -I {} isort --src-path="{}" ${isort_extra_args} "{}"
@@ -122,5 +112,8 @@ git ls-files '*setup.py' | parallel 'mypy $(dirname {}) --cache-dir "$(dirname {
 
 echo "Running pytest.."
 pytest -n 10 --durations=0 --cov="$repository_path" --cov-report html
+
+# Return to the original directory
+cd -
 
 exit 0
